# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8cf8b0516219b6a15f9b80399025678facf678f5b7f27dfefc81315ac988b91ae8b09d183dae1fe5df5f95e828c86b1ee578ad3e00bdfe948a9746f5b2b1028c

test:
  secret_key_base: 939387431c3e9caed92da90c9ac6853582112cafb9bb90cbc3400172eed7a92967b1af092b2154a92aae431658d6fb5ee87b3f445a10f2acf13f8ffb02fa62ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
